[package]
name = "winit"
version = "0.21.0"
authors = ["The winit contributors", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Cross-platform window creation library."
edition = "2018"
keywords = ["windowing"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-windowing/winit"
documentation = "https://docs.rs/winit"
categories = ["gui"]

[package.metadata.docs.rs]
features = ["serde_feature"]

[features]
web-sys = ["web_sys", "wasm-bindgen", "instant/wasm-bindgen"]
stdweb = ["std_web", "instant/stdweb"]
serde_feature = ["winit_types/serde_feature", "serde"]

[dependencies]
instant = "0.1.2"
lazy_static = "1.4.0"
libc = "0.2.66"
log = "0.4.8"
serde = { version = "1.0.104", optional = true, features = ["serde_derive"] }
raw-window-handle = "0.3.3"
winit_types = { version = "0.1.0", path = "../winit_types" }
glutin_interface = { version = "0.1.0", path = "../glutin_interface" }
bitflags = "1.2.1"

[dev-dependencies]
image = "0.22.4"
simple_logger = "1.4.0"

[target.'cfg(target_os = "android")'.dependencies]
ndk = { path = "../android-ndk-rs/ndk" }
ndk-glue = { path = "../android-ndk-rs/ndk-glue" }
ndk-sys = { path = "../android-ndk-rs/ndk-sys" }

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2.7"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.20.0"
core-foundation = "0.7.0"
core-graphics = "0.19.0"
dispatch = "0.2.0"
objc = "0.2.7"

[target.'cfg(target_os = "macos")'.dependencies.core-video-sys]
version = "0.1.3"
default_features = false
features = ["display_link"]

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.8"
features = [
    "combaseapi",
    "commctrl",
    "dwmapi",
    "errhandlingapi",
    "hidusage",
    "libloaderapi",
    "objbase",
    "ole2",
    "processthreadsapi",
    "shellapi",
    "shellscalingapi",
    "shobjidl_core",
    "unknwnbase",
    "winbase",
    "windowsx",
    "winerror",
    "wingdi",
    "winnt",
    "winuser",
]

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
wayland-client = { version = "0.23.0", features = [ "dlopen", "egl", "cursor", "eventloop"] }
mio = "0.6.21"
mio-extras = "2.0.6"
smithay-client-toolkit = "0.6.4"
glutin_x11_sym = { version = "0.1.0", path = "../glutin_x11_sym" }
percent-encoding = "2.1.0"
x11-dl = "2.18.4"

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd", target_os = "windows"))'.dependencies]
parking_lot = "0.10.0"

[target.'cfg(target_arch = "wasm32")'.dependencies.web_sys]
package = "web-sys"
version = "0.3.22"
optional = true
features = [
    'console',
    'CssStyleDeclaration',
    'BeforeUnloadEvent',
    'Document',
    'DomRect',
    'Element',
    'Event',
    'EventTarget',
    'FocusEvent',
    'HtmlCanvasElement',
    'HtmlElement',
    'KeyboardEvent',
    'MouseEvent',
    'Node',
    'PointerEvent',
    'Window',
    'WheelEvent'
]

[target.'cfg(target_arch = "wasm32")'.dependencies.wasm-bindgen]
version = "0.2.58"
optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies.std_web]
package = "stdweb"
version = "=0.4.20"
optional = true
features = ["experimental_features_which_may_break_on_minor_version_bumps"]

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_log = "0.1.2"
